In [1]:
#Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import tabula

In [2]:
#Reading the file
df=tabula.read_pdf('River-Water.pdf',pages='all')

Got stderr: Sep 21, 2021 2:45:39 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO: Your current java version is: 1.8.0_181
Sep 21, 2021 2:45:39 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO: To get higher rendering speed on old java 1.8 or 9 versions,
Sep 21, 2021 2:45:39 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   update to the latest 1.8 or 9 version (>= 1.8.0_191 or >= 9.0.4),
Sep 21, 2021 2:45:39 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   or
Sep 21, 2021 2:45:39 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
Sep 21, 2021 2:45:39 PM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFO:   or call System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider")

In [11]:
df[0]

,Statio\rn Code,LOCATION,STATE,Temperature\r(0 C),Dissolved\rOxygen\r(mg/ L),pH,Conductivity\r(Î¼mho/ Cm),Bio-Chemical\rOxygen\rDemand (mg/L),Nitrate\r(mg/ L),Faecal Coliform\r(MPN/ 100 mL),...,Faecal\rStreptococci\r(MPN/ 100 mL),Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
2,1001.0,BEAS AT U/S MANALI,HIMACHAL\rPRADESH,2,13,8.7,11.2,7.3,8.4,90,...,0.1,0.2,0.2,0.31,12,33,120,240,-,-
3,4444.0,RIVER BEAS D/S OF WPF AT\rMANALI,HIMACHAL\rPRADESH,8,14,8.5,10.8,7.3,8.1,62,...,0.1,0.8,0.2,0.2,31,94,280,540,-,-
4,4037.0,RIVER BEAS D/S MANALSU\rNALLAH,HIMACHAL\rPRADESH,2,13,8.9,10.9,7,8.3,68,...,0.1,1,0.1,0.1,20,32,120,280,-,-
5,2601.0,BEAS AT D/S MANALI,HIMACHAL\rPRADESH,3,14,8.2,11.1,6.9,8.2,78,...,0.1,0.6,0.1,0.4,25,170,280,920,-,-
6,2602.0,BEAS AT U/S KULLU,HIMACHAL\rPRADESH,5,15,7.6,11.5,7,8.6,63,...,0.1,0.4,0.1,0.2,25,70,220,540,-,-
7,4445.0,RIVER BEAS D/S OF WPF AT\rKULLU,HIMACHAL\rPRADESH,9,13,7.8,11.1,7.5,8,73,...,0.3,1.4,0.2,0.4,40,94,350,540,-,-
8,1002.0,BEAS AT D/S KULU,HIMACHAL\rPRADESH,6,13,7.8,11.3,7.4,8.4,66,...,0.2,0.8,0.03,0.36,39,110,220,920,-,-
9,1003.0,BEAS AT D/S AUT,HIMACHAL\rPRADESH,6,15,8.7,11,7.3,8.1,50,...,0.1,0.4,0.1,0.13,26,94,150,430,-,-
10,1004.0,BEAS AT U/S PANDOH DAM,HIMACHAL\rPRADESH,10,19,8.6,11,7.5,8.4,62,...,0.1,0.4,0.1,0.1,13,40,170,280,-,-
11,2603.0,BEAS AT D/S PANDOH DAM,HIMACHAL\rPRADESH,9,24,7.2,11.3,7.2,8.1,74,...,0.1,0.4,0.1,0.2,22,110,240,350,-,-
12,1005.0,BEAS AT EXIT OF TUNNEL\rDEHAL POWER HOUSE,HIMACHAL\rPRADESH,14,24,7.9,9.9,7.8,8.6,83,...,0.1,0.4,0.1,0.14,26,49,130,350,-,-
13,1550.0,BEAS U/S MANDI,HIMACHAL\rPRADESH,7,22,7.1,10.2,7.7,8.4,73,...,0.1,0.2,0.1,0.2,17,27,120,280,-,-
14,1006.0,BEAS AT D/S MANDI,HIMACHAL\rPRADESH,8,24,8.1,11.2,7.6,8.5,75,...,0.2,0.6,0.02,0.92,31,350,340,1600,-,-
15,2604.0,BEAS AT D/S JAISINGHPUR,HIMACHAL\rPRADESH,8.5,16,9,10.5,7.4,8.6,129,...,0.1,0.5,0.5,1.3,2,6,39,170,-,-
16,1007.0,BEAS AT D/S ALAMPUR,HIMACHAL\rPRADESH,8.5,14,9,10.3,7.5,8.1,122.8,...,0.1,0.5,0.47,1.41,2,6,47,150,-,-
17,3855.0,"BEAS D/S NADAUN BRIDGE,\rVILL BHADOLI",HIMACHAL\rPRADESH,8.5,20,9,11.5,7.3,8.1,176,...,0.1,0.4,0.2,1.2,2,6.1,40,170,-,-

In [12]:
df[0].iloc[0]

Statio\rn Code                                       1001
LOCATION                               BEAS AT U/S MANALI
STATE                                   HIMACHAL\rPRADESH
Temperature\r(0 C)                                      2
Dissolved\rOxygen\r(mg/ L)                             13
pH                                                    8.7
Conductivity\r(Î¼mho/ Cm)                             11.2
Bio-Chemical\rOxygen\rDemand (mg/L)                   7.3
Nitrate\r(mg/ L)                                      8.4
Faecal Coliform\r(MPN/ 100 mL)                         90
Total Coliform\r(MPN/ 100 mL)                         179
Faecal\rStreptococci\r(MPN/ 100 mL)                   0.1
Unnamed: 0                                            0.2
Unnamed: 1                                            0.2
Unnamed: 2                                           0.31
Unnamed: 3                                             12
Unnamed: 4                                             33
Unnamed: 5                                            120
Unnamed: 6                                            240
Unnamed: 7                                              -
Unnamed: 8                                              -
Name: 2, dtype: object

In [13]:
len(df)

82

In [14]:
df[0].iloc[2:]

,Statio\rn Code,LOCATION,STATE,Temperature\r(0 C),Dissolved\rOxygen\r(mg/ L),pH,Conductivity\r(Î¼mho/ Cm),Bio-Chemical\rOxygen\rDemand (mg/L),Nitrate\r(mg/ L),Faecal Coliform\r(MPN/ 100 mL),...,Faecal\rStreptococci\r(MPN/ 100 mL),Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
4,4037.0,RIVER BEAS D/S MANALSU\rNALLAH,HIMACHAL\rPRADESH,2,13,8.9,10.9,7,8.3,68,...,0.1,1,0.1,0.1,20,32,120,280,-,-
5,2601.0,BEAS AT D/S MANALI,HIMACHAL\rPRADESH,3,14,8.2,11.1,6.9,8.2,78,...,0.1,0.6,0.1,0.4,25,170,280,920,-,-
6,2602.0,BEAS AT U/S KULLU,HIMACHAL\rPRADESH,5,15,7.6,11.5,7,8.6,63,...,0.1,0.4,0.1,0.2,25,70,220,540,-,-
7,4445.0,RIVER BEAS D/S OF WPF AT\rKULLU,HIMACHAL\rPRADESH,9,13,7.8,11.1,7.5,8,73,...,0.3,1.4,0.2,0.4,40,94,350,540,-,-
8,1002.0,BEAS AT D/S KULU,HIMACHAL\rPRADESH,6,13,7.8,11.3,7.4,8.4,66,...,0.2,0.8,0.03,0.36,39,110,220,920,-,-
9,1003.0,BEAS AT D/S AUT,HIMACHAL\rPRADESH,6,15,8.7,11,7.3,8.1,50,...,0.1,0.4,0.1,0.13,26,94,150,430,-,-
10,1004.0,BEAS AT U/S PANDOH DAM,HIMACHAL\rPRADESH,10,19,8.6,11,7.5,8.4,62,...,0.1,0.4,0.1,0.1,13,40,170,280,-,-
11,2603.0,BEAS AT D/S PANDOH DAM,HIMACHAL\rPRADESH,9,24,7.2,11.3,7.2,8.1,74,...,0.1,0.4,0.1,0.2,22,110,240,350,-,-
12,1005.0,BEAS AT EXIT OF TUNNEL\rDEHAL POWER HOUSE,HIMACHAL\rPRADESH,14,24,7.9,9.9,7.8,8.6,83,...,0.1,0.4,0.1,0.14,26,49,130,350,-,-
13,1550.0,BEAS U/S MANDI,HIMACHAL\rPRADESH,7,22,7.1,10.2,7.7,8.4,73,...,0.1,0.2,0.1,0.2,17,27,120,280,-,-
14,1006.0,BEAS AT D/S MANDI,HIMACHAL\rPRADESH,8,24,8.1,11.2,7.6,8.5,75,...,0.2,0.6,0.02,0.92,31,350,340,1600,-,-
15,2604.0,BEAS AT D/S JAISINGHPUR,HIMACHAL\rPRADESH,8.5,16,9,10.5,7.4,8.6,129,...,0.1,0.5,0.5,1.3,2,6,39,170,-,-
16,1007.0,BEAS AT D/S ALAMPUR,HIMACHAL\rPRADESH,8.5,14,9,10.3,7.5,8.1,122.8,...,0.1,0.5,0.47,1.41,2,6,47,150,-,-
17,3855.0,"BEAS D/S NADAUN BRIDGE,\rVILL BHADOLI",HIMACHAL\rPRADESH,8.5,20,9,11.5,7.3,8.1,176,...,0.1,0.4,0.2,1.2,2,6.1,40,170,-,-

In [7]:
for i in range(len(df)):
    df[i]=df[i].iloc[2:]

In [16]:
df[0]

,Statio\rn Code,LOCATION,STATE,Temperature\r(0 C),Dissolved\rOxygen\r(mg/ L),pH,Conductivity\r(Î¼mho/ Cm),Bio-Chemical\rOxygen\rDemand (mg/L),Nitrate\r(mg/ L),Faecal Coliform\r(MPN/ 100 mL),...,Faecal\rStreptococci\r(MPN/ 100 mL),Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
2,1001.0,BEAS AT U/S MANALI,HIMACHAL\rPRADESH,2,13,8.7,11.2,7.3,8.4,90,...,0.1,0.2,0.2,0.31,12,33,120,240,-,-
3,4444.0,RIVER BEAS D/S OF WPF AT\rMANALI,HIMACHAL\rPRADESH,8,14,8.5,10.8,7.3,8.1,62,...,0.1,0.8,0.2,0.2,31,94,280,540,-,-
4,4037.0,RIVER BEAS D/S MANALSU\rNALLAH,HIMACHAL\rPRADESH,2,13,8.9,10.9,7,8.3,68,...,0.1,1,0.1,0.1,20,32,120,280,-,-
5,2601.0,BEAS AT D/S MANALI,HIMACHAL\rPRADESH,3,14,8.2,11.1,6.9,8.2,78,...,0.1,0.6,0.1,0.4,25,170,280,920,-,-
6,2602.0,BEAS AT U/S KULLU,HIMACHAL\rPRADESH,5,15,7.6,11.5,7,8.6,63,...,0.1,0.4,0.1,0.2,25,70,220,540,-,-
7,4445.0,RIVER BEAS D/S OF WPF AT\rKULLU,HIMACHAL\rPRADESH,9,13,7.8,11.1,7.5,8,73,...,0.3,1.4,0.2,0.4,40,94,350,540,-,-
8,1002.0,BEAS AT D/S KULU,HIMACHAL\rPRADESH,6,13,7.8,11.3,7.4,8.4,66,...,0.2,0.8,0.03,0.36,39,110,220,920,-,-
9,1003.0,BEAS AT D/S AUT,HIMACHAL\rPRADESH,6,15,8.7,11,7.3,8.1,50,...,0.1,0.4,0.1,0.13,26,94,150,430,-,-
10,1004.0,BEAS AT U/S PANDOH DAM,HIMACHAL\rPRADESH,10,19,8.6,11,7.5,8.4,62,...,0.1,0.4,0.1,0.1,13,40,170,280,-,-
11,2603.0,BEAS AT D/S PANDOH DAM,HIMACHAL\rPRADESH,9,24,7.2,11.3,7.2,8.1,74,...,0.1,0.4,0.1,0.2,22,110,240,350,-,-
12,1005.0,BEAS AT EXIT OF TUNNEL\rDEHAL POWER HOUSE,HIMACHAL\rPRADESH,14,24,7.9,9.9,7.8,8.6,83,...,0.1,0.4,0.1,0.14,26,49,130,350,-,-
13,1550.0,BEAS U/S MANDI,HIMACHAL\rPRADESH,7,22,7.1,10.2,7.7,8.4,73,...,0.1,0.2,0.1,0.2,17,27,120,280,-,-
14,1006.0,BEAS AT D/S MANDI,HIMACHAL\rPRADESH,8,24,8.1,11.2,7.6,8.5,75,...,0.2,0.6,0.02,0.92,31,350,340,1600,-,-
15,2604.0,BEAS AT D/S JAISINGHPUR,HIMACHAL\rPRADESH,8.5,16,9,10.5,7.4,8.6,129,...,0.1,0.5,0.5,1.3,2,6,39,170,-,-
16,1007.0,BEAS AT D/S ALAMPUR,HIMACHAL\rPRADESH,8.5,14,9,10.3,7.5,8.1,122.8,...,0.1,0.5,0.47,1.41,2,6,47,150,-,-
17,3855.0,"BEAS D/S NADAUN BRIDGE,\rVILL BHADOLI",HIMACHAL\rPRADESH,8.5,20,9,11.5,7.3,8.1,176,...,0.1,0.4,0.2,1.2,2,6.1,40,170,-,-

In [60]:
obj=[df[i] for i in range(len(df))]

In [194]:
df_2=pd.concat(obj)

In [195]:
df_2.shape

(1571, 42)

In [196]:
df_2.head(10)

,Statio\rn Code,LOCATION,STATE,Temperature\r(0 C),Dissolved\rOxygen\r(mg/ L),pH,Conductivity\r(Î¼mho/ Cm),Bio-Chemical\rOxygen\rDemand (mg/L),Nitrate\r(mg/ L),Faecal Coliform\r(MPN/ 100 mL),...,Nitrate,Faecal Coliform,Temperat\rure\r(0 C),Bio-Chemical Oxygen\rDemand (mg/L),Faecal\rStreptoc\rocci\r(MPN/\r100 mL),Dissolved Oxygen\r(mg/ L),Bio-Chemical\rOxygen Demand\r(mg/L),Faecal\rStreptococci\r(MPN/ 100\rmL),Bio-Chemical\rOxygen Demand\r(Mg/L),Total Coliform (MPN/\r100 mL)
2,1001,BEAS AT U/S MANALI,HIMACHAL\rPRADESH,2,13,8.7,11.2,7.3,8.4,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4444,RIVER BEAS D/S OF WPF AT\rMANALI,HIMACHAL\rPRADESH,8,14,8.5,10.8,7.3,8.1,62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4037,RIVER BEAS D/S MANALSU\rNALLAH,HIMACHAL\rPRADESH,2,13,8.9,10.9,7,8.3,68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2601,BEAS AT D/S MANALI,HIMACHAL\rPRADESH,3,14,8.2,11.1,6.9,8.2,78,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2602,BEAS AT U/S KULLU,HIMACHAL\rPRADESH,5,15,7.6,11.5,7,8.6,63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,4445,RIVER BEAS D/S OF WPF AT\rKULLU,HIMACHAL\rPRADESH,9,13,7.8,11.1,7.5,8,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1002,BEAS AT D/S KULU,HIMACHAL\rPRADESH,6,13,7.8,11.3,7.4,8.4,66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1003,BEAS AT D/S AUT,HIMACHAL\rPRADESH,6,15,8.7,11,7.3,8.1,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1004,BEAS AT U/S PANDOH DAM,HIMACHAL\rPRADESH,10,19,8.6,11,7.5,8.4,62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2603,BEAS AT D/S PANDOH DAM,HIMACHAL\rPRADESH,9,24,7.2,11.3,7.2,8.1,74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [197]:
df_2.columns

Index(['Statio\rn Code', 'LOCATION', 'STATE', 'Temperature\r(0 C)',
       'Dissolved\rOxygen\r(mg/ L)', 'pH', 'Conductivity\r(Î¼mho/ Cm)',
       'Bio-Chemical\rOxygen\rDemand (mg/L)', 'Nitrate\r(mg/ L)',
       'Faecal Coliform\r(MPN/ 100 mL)', 'Total Coliform\r(MPN/ 100 mL)',
       'Faecal\rStreptococci\r(MPN/ 100 mL)', 'Unnamed: 0', 'Unnamed: 1',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Bio-Chemical\rOxygen\rDemand (Mg/L)',
       'Total Coliform (MPN/ 100\rmL)', 'Dissolved', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Faecal -\rStreptococci\r(MPN/ 100 mL)',
       'Bio-Chemical', 'Faecal', 'Temperature', 'Dissolved\rOxygen', 'Nitrate',
       'Faecal Coliform', 'Temperat\rure\r(0 C)',
       'Bio-Chemical Oxygen\rDemand (mg/L)',
       'Faecal\rStreptoc\rocci\r(MPN/\r100 mL)', 'Dissolved Oxygen\r(mg/ L)',
       'Bio-Chemical\rOxygen Demand\r(mg/L)',
       'Faecal\rStreptococci\r(MPN/ 100\rmL)',
       'Bio-Chemical\rOxygen Demand\r(Mg/L)', 'Total Coliform (MPN/\r100 mL)'],
      dtype='object')

In [198]:
df_2=df_2[['Statio\rn Code', 'LOCATION', 'STATE', 'Temperature\r(0 C)','Dissolved\rOxygen\r(mg/ L)', 'pH', 'Conductivity\r(Î¼mho/ Cm)','Bio-Chemical\rOxygen\rDemand (mg/L)', 'Nitrate\r(mg/ L)','Faecal Coliform\r(MPN/ 100 mL)', 'Total Coliform\r(MPN/ 100 mL)','Faecal\rStreptococci\r(MPN/ 100 mL)', 'Unnamed: 0', 'Unnamed: 1','Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6','Unnamed: 7', 'Unnamed: 8']]

In [199]:
df_2.shape

(1571, 21)

In [200]:
df_2

,Statio\rn Code,LOCATION,STATE,Temperature\r(0 C),Dissolved\rOxygen\r(mg/ L),pH,Conductivity\r(Î¼mho/ Cm),Bio-Chemical\rOxygen\rDemand (mg/L),Nitrate\r(mg/ L),Faecal Coliform\r(MPN/ 100 mL),...,Faecal\rStreptococci\r(MPN/ 100 mL),Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
2,1001,BEAS AT U/S MANALI,HIMACHAL\rPRADESH,2,13,8.7,11.2,7.3,8.4,90,...,0.1,0.2,0.2,0.31,12,33,120,240,-,-
3,4444,RIVER BEAS D/S OF WPF AT\rMANALI,HIMACHAL\rPRADESH,8,14,8.5,10.8,7.3,8.1,62,...,0.1,0.8,0.2,0.2,31,94,280,540,-,-
4,4037,RIVER BEAS D/S MANALSU\rNALLAH,HIMACHAL\rPRADESH,2,13,8.9,10.9,7,8.3,68,...,0.1,1,0.1,0.1,20,32,120,280,-,-
5,2601,BEAS AT D/S MANALI,HIMACHAL\rPRADESH,3,14,8.2,11.1,6.9,8.2,78,...,0.1,0.6,0.1,0.4,25,170,280,920,-,-
6,2602,BEAS AT U/S KULLU,HIMACHAL\rPRADESH,5,15,7.6,11.5,7,8.6,63,...,0.1,0.4,0.1,0.2,25,70,220,540,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,2387,SUBAREKHA AT GHATISLA\rROAD BRIDGE,JHARKHAND,20,NaN,7.3,7.7,NaN,7.5,188,...,0.4,0.6,-,-,-,-,-,-,-,-
11,2395,SUBARNAREKHA AT HATIA\rDAM,JHARKHAND,8,NaN,8.2,8.5,NaN,7.4,-,...,1.6,2.5,-,-,140,230,750,1200,-,-
12,2397,SUBARNAREKHA AT\rGATALSUD DAM,JHARKHAND,13,NaN,8.1,8.4,NaN,7.4,-,...,2.4,2.9,-,-,140,150,750,930,-,-
13,2399,SUBARNAREKHA AT CHANDIL\rDAM,JHARKHAND,17.5,NaN,7.4,7.8,NaN,7.6,156,...,0.3,0.8,-,-,-,-,-,-,-,-
14,1641,SUBARNAREKHA AT RAJGHAT\r(THENGUDIA),ODISHA,19,NaN,6.4,8.4,NaN,8.5,142,...,0.4,1.9,0.1,0.5,20,1700,260,3500,-,-

In [201]:
df_2.dropna(axis=0,inplace=True)

In [202]:
df_2['Unnamed: 7'].replace(to_replace=['--','-'],value=0,inplace=True)

In [203]:
df_2['Unnamed: 7'].value_counts()

0      290
170      2
79       1
23       1
31       1
Name: Unnamed: 7, dtype: int64

In [204]:
df_2['Unnamed: 8'].replace(to_replace=['--','-'],value=0,inplace=True)

In [205]:
df_2['Unnamed: 8'].value_counts()

0      290
700      1
23       1
490      1
31       1
170      1
Name: Unnamed: 8, dtype: int64

In [206]:
df_2

,Statio\rn Code,LOCATION,STATE,Temperature\r(0 C),Dissolved\rOxygen\r(mg/ L),pH,Conductivity\r(Î¼mho/ Cm),Bio-Chemical\rOxygen\rDemand (mg/L),Nitrate\r(mg/ L),Faecal Coliform\r(MPN/ 100 mL),...,Faecal\rStreptococci\r(MPN/ 100 mL),Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
2,1001,BEAS AT U/S MANALI,HIMACHAL\rPRADESH,2,13,8.7,11.2,7.3,8.4,90,...,0.1,0.2,0.2,0.31,12,33,120,240,0,0
3,4444,RIVER BEAS D/S OF WPF AT\rMANALI,HIMACHAL\rPRADESH,8,14,8.5,10.8,7.3,8.1,62,...,0.1,0.8,0.2,0.2,31,94,280,540,0,0
4,4037,RIVER BEAS D/S MANALSU\rNALLAH,HIMACHAL\rPRADESH,2,13,8.9,10.9,7,8.3,68,...,0.1,1,0.1,0.1,20,32,120,280,0,0
5,2601,BEAS AT D/S MANALI,HIMACHAL\rPRADESH,3,14,8.2,11.1,6.9,8.2,78,...,0.1,0.6,0.1,0.4,25,170,280,920,0,0
6,2602,BEAS AT U/S KULLU,HIMACHAL\rPRADESH,5,15,7.6,11.5,7,8.6,63,...,0.1,0.4,0.1,0.2,25,70,220,540,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,7,NARMADA AT GARUDESHWAR,GUJARAT,26,30,6.2,7.7,7.5,8.2,230,...,0.1,0.64,0.07,0.16,17,33,33,79,0,0
8,1244,"NARMADA AT PANETHA,",GUJARAT,25,31,6.3,7.5,7.6,8.3,217,...,0.3,0.9,0.1,0.2,13,33,32,79,0,0
9,1245,"NARMADA AT CHANDOD,",GUJARAT,20,30,7,7.8,7,8.4,204,...,0.3,0.8,0.4,0.6,4,26,33,210,0,0
10,1981,"NARMADA AT ZANOR (NTPC),\rBHARUCH",GUJARAT,26,30,6.1,7.4,7.6,8.2,235,...,0.6,0.8,BDL,BDL,21,33,46,94,0,0
11,1243,"NARMADA AT BHARUCH,\rZADESHVAR,",GUJARAT,27,30,5.9,7.1,7.7,8.2,244,...,0.7,1.1,BDL,BDL,49,110,170,390,0,0

In [207]:
df_2.drop(['Statio\rn Code','LOCATION','STATE'], axis=1, inplace=True)

In [208]:
df_2

,Temperature\r(0 C),Dissolved\rOxygen\r(mg/ L),pH,Conductivity\r(Î¼mho/ Cm),Bio-Chemical\rOxygen\rDemand (mg/L),Nitrate\r(mg/ L),Faecal Coliform\r(MPN/ 100 mL),Total Coliform\r(MPN/ 100 mL),Faecal\rStreptococci\r(MPN/ 100 mL),Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
2,2,13,8.7,11.2,7.3,8.4,90,179,0.1,0.2,0.2,0.31,12,33,120,240,0,0
3,8,14,8.5,10.8,7.3,8.1,62,92,0.1,0.8,0.2,0.2,31,94,280,540,0,0
4,2,13,8.9,10.9,7,8.3,68,135,0.1,1,0.1,0.1,20,32,120,280,0,0
5,3,14,8.2,11.1,6.9,8.2,78,218,0.1,0.6,0.1,0.4,25,170,280,920,0,0
6,5,15,7.6,11.5,7,8.6,63,149,0.1,0.4,0.1,0.2,25,70,220,540,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,26,30,6.2,7.7,7.5,8.2,230,333,0.1,0.64,0.07,0.16,17,33,33,79,0,0
8,25,31,6.3,7.5,7.6,8.3,217,331,0.3,0.9,0.1,0.2,13,33,32,79,0,0
9,20,30,7,7.8,7,8.4,204,368,0.3,0.8,0.4,0.6,4,26,33,210,0,0
10,26,30,6.1,7.4,7.6,8.2,235,2910,0.6,0.8,BDL,BDL,21,33,46,94,0,0
11,27,30,5.9,7.1,7.7,8.2,244,18300,0.7,1.1,BDL,BDL,49,110,170,390,0,0

In [218]:
df_2['Unnamed: 8'].replace(to_replace=['-','--','__','BDL'],value=0,inplace=True)

In [219]:
df_2['Unnamed: 8']=df_2['Unnamed: 8'].astype('float')

In [220]:
df_3['Faecal Streptococci (MPN/ 100 mL)']=df_2['Unnamed: 5']+df_2['Unnamed: 6']

In [221]:
df_3['Faecal Streptococci (MPN/ 100 mL)']=df_3['Total Coliform\r(MPN/ 100 mL)']/2

In [222]:
df_3['Faecal Streptococci (MPN/ 100 mL)']

2      90.00
3     205.00
4     100.00
5     300.00
6     190.00
       ...
7      28.00
8      27.75
9      60.75
10     35.00
11    140.00
Name: Faecal Streptococci (MPN/ 100 mL), Length: 295, dtype: float64

In [234]:
df_3['Conductivity (Î¼mho/ Cm)']=df_3['Conductivity\r(Î¼mho/ Cm)']

In [235]:
df_3.drop(['Conductivity\r(Î¼mho/ Cm)'],axis=1,inplace=True)

In [236]:
df_3

,Temperature,Dissolved Oxygen,pH,Bio-Chemical Oxygen Demand (mg/L),Faecal Streptococci (MPN/ 100 mL),Nitrate (mg/ L),Faecal Coliform (MPN/ 100 mL),Total Coliform (MPN/ 100 mL),Conductivity (Î¼mho/ Cm)
2,7.5,9.95,7.85,0.15,90.00,0.255,22.5,180.0,134.5
3,11.0,9.65,7.70,0.45,205.00,0.200,62.5,410.0,77.0
4,7.5,9.90,7.65,0.55,100.00,0.100,26.0,200.0,101.5
5,8.5,9.65,7.55,0.35,300.00,0.250,97.5,600.0,148.0
6,10.0,9.55,7.80,0.25,190.00,0.150,47.5,380.0,106.0
...,...,...,...,...,...,...,...,...,...
7,28.0,6.95,7.85,0.37,28.00,0.115,25.0,56.0,281.5
8,28.0,6.90,7.95,0.60,27.75,0.150,23.0,55.5,274.0
9,25.0,7.40,7.70,0.55,60.75,0.500,15.0,121.5,286.0
10,28.0,6.75,7.90,0.70,35.00,0.000,27.0,70.0,1572.5
11,28.5,6.50,7.95,0.90,140.00,0.000,79.5,280.0,9272.0

In [237]:
df_3.to_csv('Data_MADE.csv')